---
title: "hispanic-candidates-election-2024"
author: "Luciana Perez Uribe"
date: "2024-04-15"
output: html_document
---

# Install libraries
```{r}
install.packages("tidyverse")
install.packages("fuzzyjoin")
install.packages("dplyr")
install.packages("writexl")
library(writexl)
library(tidyverse)
library(dplyr)
library(fuzzyjoin)
```

# Import datasets
```{r}
nc_voter = read.delim("./data/ncvoter_Statewide.txt", sep = "\t") # downloaded July 15, 2024
candidates <- read_csv("./data/Candidate_Listing_2024.csv")
```

# Filter Hispanic/Latino voters
```{r}
hispanic_voters <- nc_voter %>%
  filter(ethnic_code == 'HL')
```

# Clean and normalize names (convert to uppercase and trim whitespace)
```{r}
hispanic_voters <- hispanic_voters %>%
  mutate(last_name = toupper(trimws(last_name)),
         first_name = toupper(trimws(first_name)),
         middle_name = toupper(trimws(middle_name)),
         county_desc = toupper(trimws(county_desc)))

candidates <- candidates %>%
  mutate(last_name = toupper(trimws(last_name)),
         first_name = toupper(trimws(first_name)),
         middle_name = toupper(trimws(middle_name)),
         county_name = toupper(trimws(county_name)))
```

# Join the databases by names
```{r}
candidates_hispanic <- candidates %>%
  inner_join(hispanic_voters, by = c("last_name", "first_name", "middle_name", "county_name" = "county_desc"))
```

# Handle duplicates if necessary
```{r}
candidates_hispanic_unique <- candidates_hispanic %>%
  select(last_name, first_name, middle_name, ethnic_code, everything()) %>%
  distinct(last_name, first_name, .keep_all = TRUE)
```

# Show Hispanic/Latino candidates
```{r}
print(candidates_hispanic_unique)
```


# Export HISPANIC_CANDIDATES into .xlsx file

```{r}
write_xlsx(candidates_hispanic_unique, "filter-hispanic-candidates_2024.xlsx")
```
