---
title: "hispanic-voters-election-2024"
author: "Luciana Perez Uribe Guinassi"
date: "2024-04-09"
output: html_document
---


#Dependencies

```{r}
#update.packages(ask = FALSE)
install.packages("dplyr")
install.packages("writexl")
library(writexl)
library(dplyr)
```

#Importing dataset

```{r}
nc_voter_db_2024 <- read.delim("./data/history_stats_20240305.txt", sep = "\t")
nc_voter_db_2020 <- read.delim("./data/history_stats_20200303.txt", sep = "\t")
nc_voter_db_2016 <- read.delim("./data/history_stats_20160315.txt", sep = "\t")
nc_voter_db_2012 <- read.delim("./data/history_stats_20120508.txt", sep = "\t")
```


# Filter by only HL
```{r}
HL_ncvoter_2024 <- filter(nc_voter_db_2024, ethnic_code == "HL")
HL_ncvoter_2020 <- filter(nc_voter_db_2020, ethnic_code == "HL")
HL_ncvoter_2016 <- filter(nc_voter_db_2016, ethnic_code == "HL")
HL_ncvoter_2012 <- filter(nc_voter_db_2012, ethnic_code == "HL")

```

# In what primary did latinos registered as unaffiliated participate in? 2024
```{r}
unaffiliated_ncvoter_HL_2024 <- filter(HL_ncvoter_2024, party_cd == "UNA")
sum(unaffiliated_ncvoter_HL_2024$total_voters, na.rm = TRUE)
unique_party_cd_HL <- unique(unaffiliated_ncvoter_HL_2024$voted_party_cd)
for (party in unique_party_cd_HL) {
  filtered_data <- filter(unaffiliated_ncvoter_HL_2024, voted_party_cd == party)
  cat("Party:", party, "- Total Voters:", sum(filtered_data$total_voters, na.rm = TRUE), "\n")
  #assign(paste0("unaffiliated_ncvoter_2024_voted_", party), filtered_data)
}
```

# In what primary did latinos registered as unaffiliated participate in? 2020
```{r}
unaffiliated_ncvoter_HL_2020 <- filter(HL_ncvoter_2020, party_cd == "UNA")
sum(unaffiliated_ncvoter_HL_2020$total_voters, na.rm = TRUE)
unique_party_cd_HL <- unique(unaffiliated_ncvoter_HL_2020$voted_party_cd)
for (party in unique_party_cd_HL) {
  filtered_data <- filter(unaffiliated_ncvoter_HL_2020, voted_party_cd == party)
  cat("Party:", party, "- Total Voters:", sum(filtered_data$total_voters, na.rm = TRUE), "\n")
  #assign(paste0("unaffiliated_ncvoter_2024_voted_", party), filtered_data)
}
```

# In what primary did latinos registered as unaffiliated participate in? 2016
```{r}
unaffiliated_ncvoter_HL_2016 <- filter(HL_ncvoter_2016, party_cd == "UNA")
sum(unaffiliated_ncvoter_HL_2016$total_voters, na.rm = TRUE)
unique_party_cd_HL <- unique(unaffiliated_ncvoter_HL_2016$voted_party_cd)
for (party in unique_party_cd_HL) {
  filtered_data <- filter(unaffiliated_ncvoter_HL_2016, voted_party_cd == party)
  cat("Party:", party, "- Total Voters:", sum(filtered_data$total_voters, na.rm = TRUE), "\n")
  #assign(paste0("unaffiliated_ncvoter_2024_voted_", party), filtered_data)
}
```

# In what primary did latinos registered as unaffiliated participate in? 2012
```{r}
unaffiliated_ncvoter_HL_2012 <- filter(HL_ncvoter_2012, party_cd == "UNA")
sum(unaffiliated_ncvoter_HL_2012$total_voters, na.rm = TRUE)
unique_party_cd_HL <- unique(unaffiliated_ncvoter_HL_2012$voted_party_cd)
for (party in unique_party_cd_HL) {
  filtered_data <- filter(unaffiliated_ncvoter_HL_2012, voted_party_cd == party)
  cat("Party:", party, "- Total Voters:", sum(filtered_data$total_voters, na.rm = TRUE), "\n")
  #assign(paste0("unaffiliated_ncvoter_2024_voted_", party), filtered_data)
}
```
# Export to excel
```{r}
write_xlsx(HL_ncvoter_2024, "filter-hispanic-voters_2024.xlsx")
write_xlsx(HL_ncvoter_2020, "filter-hispanic-voters_2020.xlsx")
write_xlsx(HL_ncvoter_2016, "filter-hispanic-voters_2016.xlsx")
write_xlsx(HL_ncvoter_2012, "filter-hispanic-voters_2012.xlsx")
```